services:
  - type: web
    name: kinos
    env: docker
    plan: standard
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: WEBSITE_URL
        value: https://kinos10.onrender.com
    domains:
      - api.kinos-engine.ai
    disk:
      name: kinos-data
      mountPath: /data
      sizeGB: 10
  
  - type: web
    name: kinos10
    env: python
    rootDir: website
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_URL
        value: https://kinos.onrender.com
      - key: ENVIRONMENT
        value: production
    domains:
      - kinos-engine.ai
