services:
  - type: web
    name: kinos
    env: docker
    plan: standard
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: WEBSITE_URL
        value: https://kinos10.onrender.com
      - key: PATH
        value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/render/bin
    domains:
      - api.kinos-engine.ai
    disk:
      name: kinos-data
      mountPath: /data
      sizeGB: 10
    buildCommand: |
      echo "Checking system environment..."
      uname -a
      echo "Checking for git..."
      which git || echo "Git not found in PATH"
      git --version || echo "Git version command failed"
      echo "Installing git if needed..."
      apt-get update && apt-get install -y git curl
      echo "Creating git symlinks in common locations..."
      ln -sf $(which git) /usr/local/bin/git
      ln -sf $(which git) /usr/bin/git
      mkdir -p /opt/render/bin /opt/render/project/bin
      ln -sf $(which git) /opt/render/bin/git
      ln -sf $(which git) /opt/render/project/bin/git
      echo "Verifying git installation..."
      git --version
      echo "Git location: $(which git)"
  
  - type: web
    name: kinos10
    env: python
    rootDir: website
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_URL
        value: https://kinos.onrender.com
      - key: ENVIRONMENT
        value: production
    domains:
      - kinos-engine.ai
