services:
  - type: web
    name: kinos
    env: docker
    plan: standard
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
    disk:
      name: kinos-data
      mountPath: /data
      sizeGB: 10
  
  - type: web
    name: kinos-website
    env: python
    rootDir: website
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
